* Introduction
The Entelect challenge this year (2019) has a console runner.  It can
be hard to follow the output of the runner because it just prints the
entire history of the game into the console.  This project pages
through the output so that you can see the game as though it were
being rendered to the console rather than logged.

* Requirements
 - Emacs
 - Bash

* Quick Start
Simply run ~./watch.sh <path-to-root-of-entelect-challenge-repo>~
*from the root of this project* and it'll display the game in the
console using the configuration set in the =game-runner= directory of
the Entelect Challenge repo.  Change the configuration in that
directory to change what game to play/watch.

* Features

** History Scrolling
You can scroll through the history of a game which is currently
playing with the =n= (for next) and =p= (for previous) keys.  To
resume the live game, you can hit =r=.

* Coming Soon (TM)

** TODO Watch replays
** DONE Scroll through history of game
   CLOSED: [2019-04-22 Mon 13:08]
   :LOGBOOK:
   - CLOSING NOTE [2019-04-22 Mon 13:08] \\
     You can now scroll through the history of a game with `n' and `p' and
     then hit `r' to go back to watching the live game.
   :END:
** TODO Render with images rather than text
** TODO Implement error handling and user prompting
** TODO Add support for running on the starter pack rather than the source repo
